---
- name: Ensure homebrew is installed
  shell: |
    /usr/bin/ruby -e "$(curl -fsSL {{ homebrew_url }})"

- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: true

- name: Tap homebrew homebrew/cask
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"

- name: Install homebrew applications
  homebrew:
    name: "{{ apps }}"
    state: latest

- name: Install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_apps }}"
