---
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - curl
  - wget
  - zsh
  - go

# homebrew cask applications
cask_applications:
  - google-chrome
  - iterm2
  - docker
